spring.application.name=Brainworks-Admin
spring.datasource.url=jdbc:mysql://localhost:3306/brainworks
spring.datasource.username=root
spring.datasource.password=Akash@1214
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081